version: '3.8'

services:
  app:
    build: ./
    environment:
      - PORT=8090
      - IS_DEV=false
      - ADMIN_PW=SuperSecretPassword
    ports:
      - 8090:8090
    volumes:
      - ./data:/app/data
